# Numpy

NumPy is the fundamental package for scientific computing in Python.
https://www.numpy.org/

In [2]:
import numpy as np

In [3]:
np.__version__

'1.16.2'

### Array

numpy.array()

In [4]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

### Matrix

numpy.matrix() 

In [5]:
b = np.matrix([[1,2],[3,4]])
b

matrix([[1, 2],
        [3, 4]])

### Dtype


int8 = Byte (-128 to 127) <br>
int16 = Integer (-32768 to 32767) <br>
int32 = Integer (-2147483648 to +2147483647) <br>
int64 = Integer (-9223372036854775808 to +9223372036854775807) <br>
Boolean = (True or False) stored as a byte <br>
float = Shorthand for float64 : Double precision float: sign bit, 11 bits <br> exponent, 52 bits mantissa <br>
complex = Shorthand for complex128 : Complex number<br>

In [6]:
np.array([1, 2, 3], dtype='int8')

array([1, 2, 3], dtype=int8)

### Array creation


Numpy provides many functions to create arrays:



In [33]:
my_zeros = np.zeros((3,2)) 
my_zeros 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
my_ones = np.ones((3,2))
my_ones 

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
c = np.full((2,2), 7)
c

array([[7, 7],
       [7, 7]])

In [42]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [43]:
e = np.random.random((2,2))
e

array([[0.87657648, 0.48093308],
       [0.07308223, 0.72437352]])

## Sequences


In [28]:
np.arange(1,10,3,dtype='float') 

array([1., 4., 7.])

In [29]:
np.linspace(1, 10, 4) 

array([ 1.,  4.,  7., 10.])

## Computational operators

### Multiplication


@   or   numpy.dot()


<img src="../data/jupyter data/numpy dot.jpg">

In [9]:
a @ a 

array([[ 7, 10],
       [15, 22]])

In [10]:
np.dot(a,a) 

array([[ 7, 10],
       [15, 22]])

numpy.multiply()


عکس

In [12]:
np.multiply(a,a) 

array([[ 1,  4],
       [ 9, 16]])

numpy.prod()

In [13]:
np.prod(a) 

24

### Broadcasting


In [14]:
my_array = np.array([1, 2, 3]) 
my_array + 5 

array([6, 7, 8])

In [15]:
a = np.ones((3,3))
b = np.array([5, 6, 7]) 
a + b  

array([[6., 7., 8.],
       [6., 7., 8.],
       [6., 7., 8.]])

In [16]:
a = np.ones((3,1)) 
b = np.array([5, 6, 7]) 
a + b 


array([[6., 7., 8.],
       [6., 7., 8.],
       [6., 7., 8.]])

### Summation


In [17]:
np.sum(a)

3.0

In [18]:
np.cumsum(a, axis=0) 

array([[1.],
       [2.],
       [3.]])

### Subtraction


In [19]:
np.subtract(a, a) 

array([[0.],
       [0.],
       [0.]])

### division


In [20]:
np.divide([5, 6, 7],3) 

array([1.66666667, 2.        , 2.33333333])

In [21]:
np.floor_divide([5,6,7],3) 

array([1, 2, 2], dtype=int32)

### Math

Numpy.math()


In [23]:
np.math.sqrt(5)

2.23606797749979

In [24]:
np.math.nan 

nan

In [25]:
np.math.inf 

inf

### np.math.inf 

In [26]:
np.random.uniform(1,5,(2,3)) 

array([[1.76715679, 1.3393302 , 1.61031043],
       [3.81391967, 4.97257308, 3.89687053]])

In [27]:
np.random.standard_normal((5,)) 

array([ 0.07110211, -0.35614518,  0.22887422,  0.59659598,  0.74886436])

### Mask


In [30]:
my_mask = a>2 
a[my_mask] 

array([], dtype=float64)

In [31]:
my_mask2 = np.logical_and(a>1,a<4)
a[my_mask2] 

array([], dtype=float64)

### Sort


In [37]:
a = np.array([[1,4],[3,2]])
print(a) 
np.sort(a, axis=0) 

[[1 4]
 [3 2]]


array([[1, 2],
       [3, 4]])

In [38]:
np.argsort(a) 

array([[0, 1],
       [1, 0]], dtype=int64)

### Data Analysis


In [39]:
a = np.array([1, 2, 3, 4, 1, 3]) # a set 
a 

array([1, 2, 3, 4, 1, 3])